apiVersion: v2
name: python-bootstrap-infra
description: GitOps configuration for Python Bootstrap Application
type: application
version: 1.0.1
appVersion: "1.0.1"

dependencies:
  - name: k8s-helm-templates
    version: "0.0.3"
    repository: "https://rg-hermann.github.io/k8s-helm-templates/"
